# Generated by Django 3.1 on 2021-04-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
